import { generateCertificatePDF } from './pdfGenerator';

export const sendCertificateEmail = async (certificate, attendee, emailSettings) => {
  try {
    // This would integrate with your email service (SendGrid, Mailgun, etc.)
    const emailData = {
      to: attendee.email,
      from: {
        email: emailSettings.fromEmail,
        name: emailSettings.fromName
      },
      subject: `Your Certificate for ${certificate.data.courseEventTitle}`,
      html: generateCertificateEmailTemplate(certificate, attendee),
      attachments: [
        {
          filename: `certificate-${certificate.certificateId}.pdf`,
          content: await generateCertificatePDF(certificate),
          type: 'application/pdf'
        }
      ]
    };

    // Mock email sending - replace with actual email service
    console.log('Sending email:', emailData);
    
    // Simulate async email sending
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    return { success: true, messageId: `msg_${Date.now()}` };
  } catch (error) {
    console.error('Error sending email:', error);
    throw error;
  }
};

const generateCertificateEmailTemplate = (certificate, attendee) => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Your Certificate</title>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
        .content { background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; }
        .certificate-info { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #667eea; }
        .footer { text-align: center; margin-top: 30px; color: #666; font-size: 14px; }
        .button { display: inline-block; background: #667eea; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; margin: 10px 0; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🎉 Congratulations!</h1>
          <p>Your certificate is ready</p>
        </div>
        
        <div class="content">
          <p>Dear <strong>${attendee.name}</strong>,</p>
          
          <p>Congratulations on successfully completing <strong>${certificate.data.courseEventTitle}</strong>!</p>
          
          <div class="certificate-info">
            <h3>Certificate Details:</h3>
            <ul>
              <li><strong>Event:</strong> ${certificate.data.courseEventTitle}</li>
              <li><strong>Completion Date:</strong> ${certificate.data.completionDate}</li>
              <li><strong>Certificate ID:</strong> ${certificate.certificateId}</li>
              <li><strong>Issued By:</strong> ${certificate.data.signingAuthorityName}</li>
            </ul>
          </div>
          
          <p>Your certificate is attached to this email as a PDF file. You can also verify its authenticity using the certificate ID on our verification page.</p>
          
          <p>Thank you for your participation, and we look forward to seeing you in future events!</p>
          
          <div class="footer">
            <p>This certificate was generated by CertifyPro Certificate Management System</p>
            <p>If you have any questions, please contact us at support@certifypro.com</p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `;
};